name: notion-snap-reborn
base: core22
version: '1.0.1'
summary: Notion Snap Reborn
description: 'Remake of the Notion Snap for Ubuntu'
grade: stable
confinement: classic

parts:
  notion-snap-reborn:
    plugin: node
    nodejs-version: 'lts/*'
    source: .
    override-build: |
      npm install
      npm run dist
