on:
  push:
    branches:
      - develop

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Create Pull Request
        uses: diillson/auto-pull-request@v1.0.1
        with:
          destination_branch: "main"
