on:
  push:
    branches:
      - develop

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Create Pull Request
        uses: diillson/auto-pull-request@v1.0.1
        with:
          destination_branch: "main"
