on:
  push:
    branches:
      - develop

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Create Pull Request
        uses: diillson/auto-pull-request@v1.0.1
        with:
          destination_branch: "main"
