on:
  push:
    branches:
      - develop

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Create Pull Request
        uses: diillson/auto-pull-request@v1.0.1
        with:
          destination_branch: "main"
